spring.application.name=jiraclone

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/jira_clone_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=K7pXv3s6A9D$G-KaPdSgVkYp3s5v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)J@NcRf
app.jwt.expiration-ms=86400000